# Generated by Django 5.2.6 on 2025-10-20 08:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportReceipt',
            fields=[
                ('export_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_address', models.CharField(max_length=255)),
                ('export_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_export_order', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('note', models.TextField(blank=True, null=True)),
                ('delivery_status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('shipping', 'Đang vận chuyển'), ('delivered', 'Đã giao')], default='pending', max_length=20)),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-export_date'],
            },
        ),
        migrations.CreateModel(
            name='ExportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_details', to='inventory.product')),
                ('export_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_details', to='transactions.exportreceipt')),
            ],
        ),
        migrations.CreateModel(
            name='ImportReceipt',
            fields=[
                ('import_id', models.AutoField(primary_key=True, serialize=False)),
                ('import_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_import_order', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_receipts', to='partners.supplier')),
            ],
            options={
                'ordering': ['-import_date'],
            },
        ),
        migrations.CreateModel(
            name='ImportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_details', to='inventory.product')),
                ('import_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_details', to='transactions.importreceipt')),
            ],
        ),
    ]
