# Generated by Django 5.2.6 on 2025-10-18 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('partners', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exportreceipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exportdetail',
            name='export_receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.exportreceipt'),
        ),
        migrations.AddField(
            model_name='importdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='importreceipt',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.supplier'),
        ),
        migrations.AddField(
            model_name='importreceipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importdetail',
            name='import_receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.importreceipt'),
        ),
    ]
