# Generated by Django 5.2.6 on 2025-10-15 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportreceipt',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='importreceipt',
            name='warehouse',
        ),
    ]
