# Generated by Django 5.2.6 on 2025-10-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('transactions', '0002_remove_exportreceipt_warehouse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
